allowBuilds:
  '@prisma/client': true
  '@scarf/scarf': true
  'better-sqlite3': true
  'esbuild': true

overrides:
  'better-call': '>=1.3.5'

supportedArchitectures:
  os:
  - win32
  - linux
  - darwin
  - freebsd
  - openbsd
  - any
  cpu:
  - x64
  - arm64
  - wasm32
  libc:
  - unknown
  - any
